import type { ReactNode } from "react"
import Head from "next/head"
import Navbar from "@/components/Navbar"

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>Reducio 🔮</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex h-full flex-col  p-6">
        <Navbar />
        {children}
      </main>
    </>
  )
}

export default Layout
